engines:
  eslint:
    enabled: true
    checks:
      strict:
        enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 99
  fixme:
    enabled: true
ratings:
  paths:
  - src/client/**
  - src/commom/**
  - src/server/**
  - "**.js"
exclude_paths:
- "**/vendor/**/*"
- "**/node_modules/**/*"
- "**/bower_components/**/*"
- src/client/lb/**
